name = input("What is your name?")
favorite_game = input("What is your favorite game?")
favorite_food = input("What is your favorite food?")
dream_job = input("What is your dream job?")
print("Hello", name, "!")
print("I heard you like", favorite_game)
print("I heard you enjoy", favorite_food)
print("I heard you want to be", dream_job)
print("Nice to meet you", name)
print("you will be an incredible programmer!")
